name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push auth-service
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }} \
            ./services/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }}

      - name: Build & push user-service
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} \
            ./services/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd traefik-test
            git pull origin main
            docker-compose pull
            docker-compose up -d --scale auth-service=3 --scale user-service=2
